### ISSUE TITLE
Power LED is on, but nothing is read

### ISSUE THREAD

**Issue by SkidFace** [2969773606/GeigerCounter-V1.1#3]
Hi there! My board is powered, but it does not read anything. The indicator LED does not turn on, nor does the buzzer make a noise. I have tried to test it with a small piece of uranium, but nothing is detected. Do you have any troubleshooting tips?

![image](https://user-images.githubusercontent.com/74504657/166406688-c198eb60-8ea4-403a-b904-5c5cd89821e1.jpg)

**Comment by j-hunter** [comment]
Based on the location of the black dot on the tube, I think it may be in backwards. The PCB shows a + at one clip (Near the power LED) and the tube is marked with a + and - as well. Not sure that's the only issue, but probably a good place to start. If possible, also check the voltage at the test point, and possibly redo the calibration step

**Comment by SkidFace** [comment]
Thank you for responding! I double checked the tub polarity and it seems to be in the right direction. Using the J2 test I get .61 V for some reason

**Comment by j-hunter** [comment]
For J2 I show 82V, but I'm running the tube a little higher than the instructions say to. (Tube reads 250V, I think that's all the supply can do)

edit:
I set it back to the recommended 57V on J2 since I see no apparent difference. It is normally adjusted with the potentiometer R100, so 0.61V would mean either it is set super low, or something isn't going right.

**Comment by SkidFace** [comment]
Closing issue after a long time as I had somehow managed to swap two of the IC's and improperly calibrated the potentiometer. Thank you for the help!
